#!/usr/bin/env python
import roscompat
from object_recognition.common.utils.training_detection_args import read_arguments
from object_recognition.pipelines import find_pipelines
from object_recognition.pipelines.detection import DetectionPipeline
import ecto
import sys
DEBUG = False

if __name__ == '__main__':
    source_params, pipeline_params, sink_params, args = read_arguments()
    pipelines = find_pipelines(pipeline_params, DetectionPipeline) #map of string name to pipeline class

    # build the plasm with all the pipelines
    for _pipeline_id, pipeline_param in pipeline_params.iteritems():
        pipeline = pipelines.get(pipeline_param['method'], False)
        if not pipeline:
            sys.stderr.write('Invalid pipeline name: %s\nMake sure that the pipeline type is defined by a TrainingPipeline class, in the name class function.' % pipeline_param['type'])
            sys.exit(-1)

        #create a plasm using the DetectionPipeline interface.
        plasm = pipeline.detect(source_params[pipeline_param['source']], sink_params[pipeline_param['sink']],
                                pipeline_param.get('submethod', None),
                                pipeline_param.get('parameters', {}), db_params, object_ids, args)

        if DEBUG:
            #render the DAG with dot
            ecto.view_plasm(plasm)

    sched = ecto.schedulers.Singlethreaded(plasm)
    sched.execute()
